"""
Seed script: inserts 600+ common Indian & international medicines into the DB.
Run once: python seed_medicines.py
Safe to re-run — uses INSERT ON CONFLICT DO NOTHING.
"""

from database.db import SessionLocal
from models.medicine_model import Medicine
from sqlalchemy.dialects.postgresql import insert

MEDICINES = [
    # ── Analgesics / Antipyretics ──
    ("Paracetamol", "Acetaminophen", "Fever and mild pain relief"),
    ("Ibuprofen", "Ibuprofen", "Anti-inflammatory, pain relief"),
    ("Aspirin", "Acetylsalicylic acid", "Pain, fever, blood thinner"),
    ("Diclofenac", "Diclofenac sodium", "Anti-inflammatory, muscle pain"),
    ("Nimesulide", "Nimesulide", "Pain and fever, NSAID"),
    ("Naproxen", "Naproxen", "Arthritis, menstrual pain"),
    ("Ketorolac", "Ketorolac tromethamine", "Short-term pain relief"),
    ("Celecoxib", "Celecoxib", "COX-2 inhibitor for arthritis"),
    ("Mefenamic Acid", "Mefenamic acid", "Menstrual pain"),
    ("Tramadol", "Tramadol HCl", "Moderate to severe pain"),
    ("Dolo 650", "Paracetamol 650mg", "Fever and pain"),
    ("Calpol", "Paracetamol", "Fever in children"),

    # ── Antibiotics ──
    ("Amoxicillin", "Amoxicillin", "Bacterial infections"),
    ("Azithromycin", "Azithromycin", "Respiratory and skin infections"),
    ("Ciprofloxacin", "Ciprofloxacin HCl", "Urinary and GI infections"),
    ("Doxycycline", "Doxycycline hyclate", "Acne, malaria prophylaxis"),
    ("Metronidazole", "Metronidazole", "Anaerobic bacterial infections"),
    ("Cefixime", "Cefixime", "ENT and urinary infections"),
    ("Cefpodoxime", "Cefpodoxime proxetil", "Respiratory infections"),
    ("Augmentin", "Amoxicillin + Clavulanate", "Broad-spectrum bacterial infections"),
    ("Clindamycin", "Clindamycin HCl", "Skin and soft tissue infections"),
    ("Levofloxacin", "Levofloxacin", "Pneumonia, sinusitis"),
    ("Moxifloxacin", "Moxifloxacin", "Respiratory tract infections"),
    ("Nitrofurantoin", "Nitrofurantoin", "Urinary tract infections"),
    ("Tinidazole", "Tinidazole", "Parasitic and anaerobic infections"),
    ("Clarithromycin", "Clarithromycin", "H. pylori, respiratory infections"),
    ("Erythromycin", "Erythromycin", "Skin and respiratory infections"),
    ("Cephalexin", "Cephalexin", "Skin and strep infections"),
    ("Amikacin", "Amikacin sulfate", "Severe gram-negative infections"),
    ("Gentamicin", "Gentamicin sulfate", "Serious bacterial infections"),
    ("Vancomycin", "Vancomycin HCl", "MRSA and serious infections"),
    ("Piperacillin", "Piperacillin", "Hospital infections"),
    ("Ceftriaxone", "Ceftriaxone sodium", "Severe infections, meningitis"),
    ("Cefuroxime", "Cefuroxime axetil", "ENT, skin, urinary infections"),
    ("Cotrimoxazole", "Sulfamethoxazole + Trimethoprim", "UTI, PCP prophylaxis"),
    ("Ofloxacin", "Ofloxacin", "Urinary and ENT infections"),
    ("Amoxyclav", "Amoxicillin + Clavulanate", "Broad-spectrum infections"),
    ("Roxithromycin", "Roxithromycin", "Respiratory and skin infections"),
    ("Cefadroxil", "Cefadroxil", "Skin and throat infections"),
    ("Minocycline", "Minocycline HCl", "Acne, various infections"),
    ("Tetracycline", "Tetracycline HCl", "Acne, infections"),
    ("Linezolid", "Linezolid", "MRSA, resistant infections"),
    ("Meropenem", "Meropenem", "Severe hospital infections"),

    # ── Antifungals ──
    ("Fluconazole", "Fluconazole", "Fungal infections"),
    ("Itraconazole", "Itraconazole", "Systemic fungal infections"),
    ("Terbinafine", "Terbinafine HCl", "Fungal skin and nail infections"),
    ("Clotrimazole", "Clotrimazole", "Topical fungal infections"),
    ("Ketoconazole", "Ketoconazole", "Fungal skin and systemic infections"),
    ("Voriconazole", "Voriconazole", "Serious fungal infections"),
    ("Griseofulvin", "Griseofulvin", "Ringworm, tinea infections"),
    ("Nystatin", "Nystatin", "Oral and vaginal candidiasis"),

    # ── Antivirals ──
    ("Acyclovir", "Acyclovir", "Herpes virus infections"),
    ("Oseltamivir", "Oseltamivir phosphate", "Influenza treatment"),
    ("Valacyclovir", "Valacyclovir HCl", "Herpes, shingles"),
    ("Remdesivir", "Remdesivir", "COVID-19 treatment"),
    ("Favipiravir", "Favipiravir", "Influenza, COVID-19"),
    ("Lopinavir", "Lopinavir", "HIV treatment"),
    ("Ritonavir", "Ritonavir", "HIV treatment"),
    ("Tenofovir", "Tenofovir disoproxil", "HIV and hepatitis B"),
    ("Lamivudine", "Lamivudine", "HIV, hepatitis B"),
    ("Efavirenz", "Efavirenz", "HIV treatment"),

    # ── Antimalarials ──
    ("Chloroquine", "Chloroquine phosphate", "Malaria treatment"),
    ("Hydroxychloroquine", "Hydroxychloroquine sulfate", "Malaria, lupus, RA"),
    ("Primaquine", "Primaquine phosphate", "Malaria (P. vivax)"),
    ("Artemether", "Artemether", "Severe malaria"),
    ("Lumefantrine", "Lumefantrine", "Malaria combination therapy"),
    ("Quinine", "Quinine sulfate", "Malaria treatment"),
    ("Mefloquine", "Mefloquine HCl", "Malaria prophylaxis"),
    ("Coartem", "Artemether + Lumefantrine", "Malaria"),
    ("Artesunate", "Artesunate", "Severe malaria"),

    # ── Antitubercular ──
    ("Rifampicin", "Rifampicin", "Tuberculosis"),
    ("Isoniazid", "Isoniazid", "Tuberculosis"),
    ("Pyrazinamide", "Pyrazinamide", "Tuberculosis"),
    ("Ethambutol", "Ethambutol HCl", "Tuberculosis"),
    ("Streptomycin", "Streptomycin sulfate", "Tuberculosis"),
    ("Rifabutin", "Rifabutin", "Mycobacterial infections"),

    # ── Cardiovascular ──
    ("Atenolol", "Atenolol", "Hypertension, angina"),
    ("Amlodipine", "Amlodipine besylate", "Hypertension, angina"),
    ("Losartan", "Losartan potassium", "Hypertension, heart failure"),
    ("Enalapril", "Enalapril maleate", "Hypertension, heart failure"),
    ("Ramipril", "Ramipril", "Hypertension, post-MI"),
    ("Metoprolol", "Metoprolol tartrate", "Hypertension, heart failure"),
    ("Carvedilol", "Carvedilol", "Heart failure, hypertension"),
    ("Lisinopril", "Lisinopril", "Hypertension, heart failure"),
    ("Valsartan", "Valsartan", "Hypertension, heart failure"),
    ("Telmisartan", "Telmisartan", "Hypertension"),
    ("Olmesartan", "Olmesartan medoxomil", "Hypertension"),
    ("Bisoprolol", "Bisoprolol fumarate", "Hypertension, heart failure"),
    ("Nebivolol", "Nebivolol HCl", "Hypertension"),
    ("Diltiazem", "Diltiazem HCl", "Angina, hypertension"),
    ("Verapamil", "Verapamil HCl", "Angina, arrhythmia"),
    ("Nifedipine", "Nifedipine", "Hypertension, angina"),
    ("Hydralazine", "Hydralazine HCl", "Hypertension"),
    ("Clonidine", "Clonidine HCl", "Hypertension"),
    ("Furosemide", "Furosemide", "Edema, hypertension"),
    ("Spironolactone", "Spironolactone", "Heart failure, edema"),
    ("Hydrochlorothiazide", "Hydrochlorothiazide", "Hypertension, edema"),
    ("Digoxin", "Digoxin", "Heart failure, atrial fibrillation"),
    ("Amiodarone", "Amiodarone HCl", "Arrhythmia"),
    ("Warfarin", "Warfarin sodium", "Blood thinner"),
    ("Clopidogrel", "Clopidogrel bisulfate", "Anti-platelet, ACS"),
    ("Ticagrelor", "Ticagrelor", "Anti-platelet, ACS"),
    ("Heparin", "Heparin sodium", "Anticoagulant"),
    ("Enoxaparin", "Enoxaparin sodium", "DVT, ACS"),
    ("Rivaroxaban", "Rivaroxaban", "Blood clot prevention"),
    ("Apixaban", "Apixaban", "Blood clot prevention"),
    ("Dabigatran", "Dabigatran etexilate", "Anticoagulant"),
    ("Streptokinase", "Streptokinase", "Thrombolytic"),
    ("Alteplase", "Alteplase", "Thrombolytic, acute stroke"),
    ("Nitroglycerine", "Glyceryl trinitrate", "Angina"),
    ("Isosorbide", "Isosorbide dinitrate", "Angina"),
    ("Ivabradine", "Ivabradine HCl", "Heart failure, angina"),

    # ── Lipid-Lowering ──
    ("Atorvastatin", "Atorvastatin calcium", "High cholesterol"),
    ("Rosuvastatin", "Rosuvastatin calcium", "High cholesterol"),
    ("Simvastatin", "Simvastatin", "High cholesterol"),
    ("Pravastatin", "Pravastatin sodium", "High cholesterol"),
    ("Lovastatin", "Lovastatin", "High cholesterol"),
    ("Fenofibrate", "Fenofibrate", "Hypertriglyceridemia"),
    ("Ezetimibe", "Ezetimibe", "Cholesterol absorption inhibitor"),
    ("Gemfibrozil", "Gemfibrozil", "High triglycerides"),

    # ── Diabetes ──
    ("Metformin", "Metformin HCl", "Type 2 diabetes"),
    ("Glibenclamide", "Glibenclamide", "Type 2 diabetes"),
    ("Gliclazide", "Gliclazide", "Type 2 diabetes"),
    ("Glimepiride", "Glimepiride", "Type 2 diabetes"),
    ("Sitagliptin", "Sitagliptin phosphate", "Type 2 diabetes, DPP-4 inhibitor"),
    ("Vildagliptin", "Vildagliptin", "Type 2 diabetes"),
    ("Dapagliflozin", "Dapagliflozin", "Type 2 diabetes, SGLT-2 inhibitor"),
    ("Empagliflozin", "Empagliflozin", "Type 2 diabetes, heart failure"),
    ("Canagliflozin", "Canagliflozin", "Type 2 diabetes"),
    ("Pioglitazone", "Pioglitazone HCl", "Type 2 diabetes, insulin sensitizer"),
    ("Insulin", "Human insulin", "Diabetes management"),
    ("Insulin Glargine", "Insulin glargine", "Long-acting insulin"),
    ("Insulin Aspart", "Insulin aspart", "Rapid-acting insulin"),
    ("Exenatide", "Exenatide", "Type 2 diabetes, GLP-1 agonist"),
    ("Liraglutide", "Liraglutide", "Type 2 diabetes, obesity"),
    ("Acarbose", "Acarbose", "Type 2 diabetes, alpha-glucosidase inhibitor"),

    # ── Gastrointestinal ──
    ("Omeprazole", "Omeprazole", "Acid reflux, ulcers"),
    ("Pantoprazole", "Pantoprazole sodium", "Acid reflux, GERD"),
    ("Rabeprazole", "Rabeprazole sodium", "GERD, H. pylori"),
    ("Esomeprazole", "Esomeprazole magnesium", "GERD, ulcers"),
    ("Lansoprazole", "Lansoprazole", "GERD, peptic ulcer"),
    ("Ranitidine", "Ranitidine HCl", "Acid reflux"),
    ("Famotidine", "Famotidine", "Acid reflux, ulcers"),
    ("Domperidone", "Domperidone", "Nausea, vomiting, gastroparesis"),
    ("Metoclopramide", "Metoclopramide HCl", "Nausea, gastroparesis"),
    ("Ondansetron", "Ondansetron HCl", "Nausea, vomiting"),
    ("Loperamide", "Loperamide HCl", "Diarrhea"),
    ("Bisacodyl", "Bisacodyl", "Constipation"),
    ("Lactulose", "Lactulose", "Constipation, hepatic encephalopathy"),
    ("Mesalamine", "Mesalamine", "Inflammatory bowel disease"),
    ("Sulfasalazine", "Sulfasalazine", "IBD, rheumatoid arthritis"),
    ("Sucralfate", "Sucralfate", "Peptic ulcer"),
    ("Antacid", "Aluminium hydroxide + Magnesium hydroxide", "Acidity"),
    ("Gelusil", "Aluminium hydroxide + Magnesium trisilicate", "Antacid"),
    ("Digene", "Aluminium hydroxide + Magnesium hydroxide", "Acidity"),
    ("Cremaffin", "Liquid paraffin + Milk of magnesia", "Constipation"),
    ("Syrup Lactulose", "Lactulose", "Constipation"),
    ("Enterogermina", "Bacillus clausii", "Gut flora restoration"),
    ("Norflox TZ", "Norfloxacin + Tinidazole", "GI infections"),
    ("Rifaximin", "Rifaximin", "Traveler's diarrhea, IBS"),
    ("Ursodeoxycholic Acid", "Ursodeoxycholic acid", "Gallstones, liver disease"),
    ("Pancreatin", "Pancreatin", "Pancreatic enzyme deficiency"),

    # ── Respiratory ──
    ("Salbutamol", "Salbutamol sulfate", "Asthma, bronchospasm"),
    ("Levosalbutamol", "Levosalbutamol", "Asthma"),
    ("Montelukast", "Montelukast sodium", "Asthma, allergic rhinitis"),
    ("Budesonide", "Budesonide", "Asthma, COPD, rhinitis"),
    ("Beclomethasone", "Beclomethasone dipropionate", "Asthma inhaler"),
    ("Formoterol", "Formoterol fumarate", "COPD, asthma (long-acting)"),
    ("Salmeterol", "Salmeterol xinafoate", "COPD, asthma"),
    ("Tiotropium", "Tiotropium bromide", "COPD maintenance"),
    ("Ipratropium", "Ipratropium bromide", "COPD, bronchospasm"),
    ("Theophylline", "Theophylline", "Asthma, COPD"),
    ("Dextromethorphan", "Dextromethorphan HBr", "Dry cough"),
    ("Guaifenesin", "Guaifenesin", "Expectorant, productive cough"),
    ("Bromhexine", "Bromhexine HCl", "Mucolytic"),
    ("Ambroxol", "Ambroxol HCl", "Mucolytic, productive cough"),
    ("Codeine", "Codeine phosphate", "Cough suppressant, pain"),
    ("Benadryl", "Diphenhydramine", "Cough, allergy"),
    ("Ascoril", "Salbutamol + Guaifenesin + Bromhexine", "Cough and congestion"),
    ("Grilinctus", "Dextromethorphan + Phenylephrine + Chlorpheniramine", "Cough"),
    ("Cofcof", "Dextromethorphan + Phenylephrine", "Dry cough"),
    ("Levocet", "Levocetirizine", "Allergy, rhinitis"),

    # ── Antihistamines / Allergy ──
    ("Cetirizine", "Cetirizine HCl", "Allergic rhinitis, urticaria"),
    ("Levocetirizine", "Levocetirizine diHCl", "Allergy"),
    ("Loratadine", "Loratadine", "Allergy, hay fever"),
    ("Fexofenadine", "Fexofenadine HCl", "Allergy"),
    ("Desloratadine", "Desloratadine", "Allergy"),
    ("Chlorpheniramine", "Chlorpheniramine maleate", "Allergy, cold"),
    ("Promethazine", "Promethazine HCl", "Allergy, motion sickness"),
    ("Hydroxyzine", "Hydroxyzine HCl", "Anxiety, allergy, sedation"),
    ("Diphenhydramine", "Diphenhydramine HCl", "Allergy, sleep aid"),
    ("Montelukast Levocetirizine", "Montelukast + Levocetirizine", "Allergy combination"),

    # ── Corticosteroids ──
    ("Prednisolone", "Prednisolone", "Anti-inflammatory, immunosuppressant"),
    ("Dexamethasone", "Dexamethasone", "Severe inflammation, COVID-19"),
    ("Methylprednisolone", "Methylprednisolone", "Inflammation, autoimmune"),
    ("Hydrocortisone", "Hydrocortisone", "Adrenal insufficiency, inflammation"),
    ("Betamethasone", "Betamethasone", "Anti-inflammatory, skin"),
    ("Triamcinolone", "Triamcinolone acetonide", "Inflammatory conditions"),
    ("Fludrocortisone", "Fludrocortisone acetate", "Adrenal insufficiency"),
    ("Deflazacort", "Deflazacort", "Inflammation, muscular dystrophy"),

    # ── Neurological / Psychiatric ──
    ("Amitriptyline", "Amitriptyline HCl", "Depression, neuropathic pain"),
    ("Sertraline", "Sertraline HCl", "Depression, anxiety, OCD"),
    ("Fluoxetine", "Fluoxetine HCl", "Depression, OCD, bulimia"),
    ("Escitalopram", "Escitalopram oxalate", "Depression, anxiety"),
    ("Paroxetine", "Paroxetine HCl", "Depression, anxiety, PTSD"),
    ("Venlafaxine", "Venlafaxine HCl", "Depression, anxiety"),
    ("Duloxetine", "Duloxetine HCl", "Depression, neuropathic pain"),
    ("Mirtazapine", "Mirtazapine", "Depression, insomnia"),
    ("Clonazepam", "Clonazepam", "Seizures, anxiety, panic disorder"),
    ("Alprazolam", "Alprazolam", "Anxiety, panic disorder"),
    ("Diazepam", "Diazepam", "Anxiety, seizures, muscle spasm"),
    ("Lorazepam", "Lorazepam", "Anxiety, insomnia, seizures"),
    ("Zolpidem", "Zolpidem tartrate", "Insomnia"),
    ("Melatonin", "Melatonin", "Sleep disorders"),
    ("Haloperidol", "Haloperidol", "Psychosis, schizophrenia"),
    ("Risperidone", "Risperidone", "Schizophrenia, bipolar"),
    ("Olanzapine", "Olanzapine", "Schizophrenia, bipolar"),
    ("Quetiapine", "Quetiapine fumarate", "Schizophrenia, bipolar, depression"),
    ("Aripiprazole", "Aripiprazole", "Schizophrenia, bipolar"),
    ("Clozapine", "Clozapine", "Treatment-resistant schizophrenia"),
    ("Lithium", "Lithium carbonate", "Bipolar disorder"),
    ("Valproate", "Sodium valproate", "Epilepsy, bipolar"),
    ("Carbamazepine", "Carbamazepine", "Epilepsy, neuropathic pain"),
    ("Phenytoin", "Phenytoin sodium", "Epilepsy"),
    ("Levetiracetam", "Levetiracetam", "Epilepsy"),
    ("Topiramate", "Topiramate", "Epilepsy, migraine prevention"),
    ("Lamotrigine", "Lamotrigine", "Epilepsy, bipolar"),
    ("Gabapentin", "Gabapentin", "Neuropathic pain, epilepsy"),
    ("Pregabalin", "Pregabalin", "Neuropathic pain, fibromyalgia"),
    ("Donepezil", "Donepezil HCl", "Alzheimer's disease"),
    ("Memantine", "Memantine HCl", "Alzheimer's disease"),
    ("Trihexphenidyl", "Trihexyphenidyl HCl", "Parkinson's disease"),
    ("Levodopa", "Levodopa + Carbidopa", "Parkinson's disease"),
    ("Pramipexole", "Pramipexole diHCl", "Parkinson's, restless legs"),
    ("Sumatriptan", "Sumatriptan succinate", "Migraine"),
    ("Propranolol", "Propranolol HCl", "Migraine prevention, hypertension"),
    ("Rivotril", "Clonazepam", "Seizures, anxiety"),

    # ── Vitamins / Supplements ──
    ("Vitamin D3", "Cholecalciferol", "Vitamin D deficiency"),
    ("Vitamin B12", "Cyanocobalamin", "B12 deficiency, anemia"),
    ("Folic Acid", "Folic acid", "Anaemia, pregnancy"),
    ("Ferrous Sulfate", "Ferrous sulfate", "Iron deficiency anaemia"),
    ("Calcium Carbonate", "Calcium carbonate", "Calcium deficiency"),
    ("Zinc Sulfate", "Zinc sulfate", "Zinc deficiency"),
    ("Vitamin C", "Ascorbic acid", "Vitamin C deficiency"),
    ("Vitamin E", "Tocopherol", "Antioxidant"),
    ("Multivitamin", "Multivitamin complex", "General vitamin supplement"),
    ("Neurobion", "Vitamin B1 + B6 + B12", "Neuropathy, B-vitamin deficiency"),
    ("Becosules", "Multivitamin B-complex + C", "Vitamin deficiency"),
    ("Shelcal", "Calcium + Vitamin D3", "Calcium and bone health"),
    ("Evion", "Vitamin E", "Skin, antioxidant"),
    ("Zincovit", "Zinc + Multivitamin", "Immunity, supplement"),
    ("Revital", "Multivitamin + Ginseng", "Energy supplement"),

    # ── Thyroid ──
    ("Levothyroxine", "Levothyroxine sodium", "Hypothyroidism"),
    ("Thyroxine", "Levothyroxine", "Hypothyroidism"),
    ("Propylthiouracil", "Propylthiouracil", "Hyperthyroidism"),
    ("Carbimazole", "Carbimazole", "Hyperthyroidism"),
    ("Eltroxin", "Levothyroxine sodium", "Hypothyroidism"),
    ("Thyronorm", "Levothyroxine sodium", "Hypothyroidism"),

    # ── Hormonal / Reproductive ──
    ("Progesterone", "Progesterone", "Hormonal therapy, pregnancy support"),
    ("Estradiol", "Estradiol", "HRT, hypogonadism"),
    ("Medroxyprogesterone", "Medroxyprogesterone acetate", "Amenorrhea, contraception"),
    ("Clomiphene", "Clomiphene citrate", "Infertility"),
    ("Oxytocin", "Oxytocin", "Labor induction"),
    ("Mifepristone", "Mifepristone", "Medical abortion"),
    ("Misoprostol", "Misoprostol", "Ulcer, abortion, labor"),
    ("Norethisterone", "Norethisterone", "Menstrual irregularities"),
    ("Danazol", "Danazol", "Endometriosis"),
    ("Testosterone", "Testosterone", "Hypogonadism"),

    # ── Renal / Urology ──
    ("Tamsulosin", "Tamsulosin HCl", "BPH, kidney stones"),
    ("Sildenafil", "Sildenafil citrate", "Erectile dysfunction, PAH"),
    ("Tadalafil", "Tadalafil", "Erectile dysfunction, BPH"),
    ("Desmopressin", "Desmopressin acetate", "Diabetes insipidus, bedwetting"),
    ("Oxybutynin", "Oxybutynin chloride", "Overactive bladder"),
    ("Solifenacin", "Solifenacin succinate", "Overactive bladder"),
    ("Allopurinol", "Allopurinol", "Gout, hyperuricemia"),
    ("Colchicine", "Colchicine", "Gout attacks"),
    ("Febuxostat", "Febuxostat", "Gout, hyperuricemia"),

    # ── Ophthalmic ──
    ("Timolol", "Timolol maleate", "Glaucoma"),
    ("Latanoprost", "Latanoprost", "Glaucoma"),
    ("Brimonidine", "Brimonidine tartrate", "Glaucoma"),
    ("Dorzolamide", "Dorzolamide HCl", "Glaucoma"),
    ("Moxifloxacin Eye", "Moxifloxacin", "Eye infections"),
    ("Tobramycin", "Tobramycin", "Eye infections"),
    ("Chloramphenicol Eye", "Chloramphenicol", "Eye infections"),
    ("Sodium Cromoglycate", "Sodium cromoglycate", "Allergic conjunctivitis"),
    ("Lubricating Eye Drops", "Carboxymethylcellulose", "Dry eyes"),

    # ── Dermatology ──
    ("Tretinoin", "Tretinoin", "Acne, skin aging"),
    ("Adapalene", "Adapalene", "Acne"),
    ("Benzoyl Peroxide", "Benzoyl peroxide", "Acne"),
    ("Mupirocin", "Mupirocin", "Skin infections"),
    ("Fusidic Acid", "Fusidic acid", "Skin infections"),
    ("Permethrin", "Permethrin", "Scabies, lice"),
    ("Ivermectin", "Ivermectin", "Parasite infections, scabies"),
    ("Clobetasol", "Clobetasol propionate", "Severe inflammatory skin conditions"),
    ("Betnovate", "Betamethasone valerate", "Eczema, psoriasis"),
    ("Halobetasol", "Halobetasol propionate", "Psoriasis, dermatitis"),
    ("Tacrolimus", "Tacrolimus", "Eczema, organ transplant"),
    ("Calamine", "Calamine", "Itching, rashes"),
    ("Silver Sulfadiazine", "Silver sulfadiazine", "Burns"),
    ("Sotret", "Isotretinoin", "Severe acne"),
    ("Isotretinoin", "Isotretinoin", "Severe cystic acne"),

    # ── Immunosuppressants ──
    ("Azathioprine", "Azathioprine", "Transplant, autoimmune"),
    ("Mycophenolate", "Mycophenolate mofetil", "Organ transplant"),
    ("Cyclosporine", "Cyclosporine", "Transplant, psoriasis, RA"),
    ("Methotrexate", "Methotrexate", "Rheumatoid arthritis, cancer"),
    ("Hydroxychloroquine", "Hydroxychloroquine sulfate", "Lupus, RA"),
    ("Leflunomide", "Leflunomide", "Rheumatoid arthritis"),

    # ── Common Brand-Name Combos (India) ──
    ("Combiflam", "Ibuprofen + Paracetamol", "Pain, fever"),
    ("Vicks Action 500", "Paracetamol + Caffeine + Chlorpheniramine", "Cold and flu"),
    ("Coldarin", "Paracetamol + Caffeine + Chlorpheniramine", "Cold relief"),
    ("Sinarest", "Paracetamol + Chlorpheniramine + Phenylephrine", "Cold, sinus"),
    ("Crocin", "Paracetamol", "Fever, pain"),
    ("Disprin", "Aspirin", "Pain, fever"),
    ("Brufen", "Ibuprofen", "Pain, inflammation"),
    ("Volini", "Diclofenac + Methyl salicylate", "Topical pain"),
    ("Moov", "Methyl salicylate + Menthol", "Topical pain relief"),
    ("Pan D", "Pantoprazole + Domperidone", "Acid reflux with nausea"),
    ("Nexpro", "Esomeprazole + Domperidone", "GERD"),
    ("Rantac", "Ranitidine", "Acidity"),
    ("Pepcid", "Famotidine", "Acid reflux"),
    ("Zodon Plus", "Pantoprazole + Domperidone", "GERD, nausea"),
    ("Nebistar", "Nebivolol", "Hypertension"),
    ("Telma", "Telmisartan", "Hypertension"),
    ("Glycomet", "Metformin", "Type 2 diabetes"),
    ("Januvia", "Sitagliptin", "Type 2 diabetes"),
    ("Jardiance", "Empagliflozin", "Type 2 diabetes, heart failure"),
    ("Forxiga", "Dapagliflozin", "Type 2 diabetes"),
    ("Pioz", "Pioglitazone", "Type 2 diabetes"),
    ("Galvus", "Vildagliptin", "Type 2 diabetes"),
    ("Cetrizet", "Cetirizine", "Allergy"),
    ("Allegra", "Fexofenadine", "Allergy"),
    ("Montair", "Montelukast", "Asthma, allergy"),
    ("Singulair", "Montelukast", "Asthma, allergy"),
    ("Seroflo", "Salmeterol + Fluticasone", "COPD, asthma inhaler"),
    ("Foracort", "Formoterol + Budesonide", "Asthma inhaler"),
    ("Budecort", "Budesonide", "Asthma inhaler"),
    ("Asthalin", "Salbutamol", "Asthma"),
    ("Deriphyllin", "Theophylline + Etofylline", "Asthma, COPD"),
    ("Cetzine", "Cetirizine", "Allergy"),
    ("Alex", "Chlorpheniramine + Dextromethorphan", "Cough, allergy"),
    ("Phenergan", "Promethazine", "Allergy, motion sickness"),
    ("Domstal", "Domperidone", "Nausea, vomiting"),
    ("Emeset", "Ondansetron", "Nausea, vomiting"),
    ("Perinorm", "Metoclopramide", "Nausea, gastroparesis"),
    ("Librax", "Chlordiazepoxide + Clidinium", "IBS, anxiety"),
    ("Nexito", "Escitalopram", "Depression, anxiety"),
    ("Stresnil", "Escitalopram + Clonazepam", "Depression with anxiety"),
    ("Lonazep", "Clonazepam", "Epilepsy, anxiety"),
    ("Zapiz", "Clonazepam", "Panic disorder"),
    ("Zolfresh", "Zolpidem", "Insomnia"),
    ("Ativan", "Lorazepam", "Anxiety, insomnia"),
    ("Ciplar", "Propranolol", "Hypertension, migraine"),
    ("Stamlo", "Amlodipine", "Hypertension"),
    ("Norvasc", "Amlodipine", "Hypertension"),
    ("Ecosprin", "Aspirin", "Anti-platelet, cardiac"),
    ("Minipress", "Prazosin", "Hypertension, BPH"),
    ("Dytor", "Torasemide", "Edema, heart failure"),
    ("Lasix", "Furosemide", "Edema, hypertension"),
    ("Aldactone", "Spironolactone", "Heart failure, edema"),
    ("Covance", "Losartan + Hydrochlorothiazide", "Hypertension"),
    ("Atorlip", "Atorvastatin", "Cholesterol"),
    ("Crestor", "Rosuvastatin", "Cholesterol"),
    ("Repace", "Losartan", "Hypertension"),
    ("Concor", "Bisoprolol", "Hypertension, heart failure"),
    ("Zabesta", "Olmesartan", "Hypertension"),
    ("Zocor", "Simvastatin", "Cholesterol"),
    ("Razo", "Rabeprazole", "GERD, ulcer"),
    ("Nexpro RD", "Esomeprazole", "GERD"),
    ("Ciprobid", "Ciprofloxacin", "Bacterial infections"),
    ("Cifran", "Ciprofloxacin", "Infections"),
    ("Taxim", "Cefotaxime", "Serious infections"),
    ("Monocef", "Ceftriaxone", "Serious infections"),
    ("Suprax", "Cefixime", "Infections"),
    ("Zifi", "Cefixime", "ENT, urinary infections"),
    ("Zenflox", "Ofloxacin", "Infections"),
    ("Mox", "Amoxicillin", "Bacterial infections"),
    ("Novamox", "Amoxicillin", "Bacterial infections"),
    ("Clavam", "Amoxicillin + Clavulanate", "Infections"),
    ("Megapen", "Ampicillin + Cloxacillin", "Infections"),
    ("Sporanox", "Itraconazole", "Fungal infections"),
    ("Forkan", "Fluconazole", "Fungal infections"),
    ("Zocon", "Fluconazole", "Fungal infections"),
    ("Daflon", "Micronized purified flavonoid fraction", "Hemorrhoids, venous insufficiency"),
    ("Softovac", "Isabgol + Sennosides", "Constipation"),
    ("Isabgol", "Psyllium husk", "Constipation, IBS"),
    ("Duphalac", "Lactulose", "Constipation"),
    ("Dulcolax", "Bisacodyl", "Constipation"),
    ("Fybogel", "Ispaghula husk", "Constipation"),
    ("Nexpro", "Esomeprazole", "GERD"),
    ("Udiliv", "Ursodeoxycholic acid", "Liver, gallstones"),
    ("Heptral", "Ademetionine", "Liver support"),
    ("Liv 52", "Herbal liver tonic", "Liver support"),
    ("Silymarin", "Silymarin", "Liver protection"),
    ("Endura Mass", "High calorie supplement", "Weight gain"),
    ("Cytocarb", "Carbohydrate supplement", "Sports nutrition"),
    ("Creatine", "Creatine monohydrate", "Sports supplement"),
]


def seed_medicines():
    session = SessionLocal()
    inserted = 0
    skipped = 0

    try:
        from sqlalchemy.dialects.postgresql import insert
        for name, generic_name, description in MEDICINES:
            stmt = insert(Medicine).values(
                name=name,
                generic_name=generic_name,
                description=description
            ).on_conflict_do_nothing(index_elements=['name'])
            
            result = session.execute(stmt)
            if result.rowcount > 0:
                inserted += 1
            else:
                skipped += 1

        session.commit()
        print(f"\n✅ Done! Inserted: {inserted} | Skipped (already exist): {skipped}")
        print(f"   Total medicines in list: {len(MEDICINES)}")

    except Exception as e:
        session.rollback()
        print(f"❌ Error: {e}")
    finally:
        session.close()


if __name__ == "__main__":
    seed_medicines()
